FROM projectmonai/monai:1.3.1

# run with:
# docker build -t ${USER}_container_nvflare --build-arg USER_ID=$(id -u) --build-arg GROUP_ID=$(id -g) . -f Dockerfile_nonroot

ENV PYTHONPATH="/code"

# Make RUN commands use `bash --login`:
SHELL ["/bin/bash", "--login", "-c"]


# some useful tools
RUN apt-get update && apt-get install vim curl git unzip graphviz nano -y && rm -rf /var/lib/apt/lists/*


# create current user inside image, so that newly created files belong to us and not to root and can be accessed outside docker as well
ARG USER_ID
ARG GROUP_ID
RUN addgroup --gid $GROUP_ID user && adduser --disabled-password --gecos '' --uid $USER_ID --gid $GROUP_ID user && usermod -a -G root user && addgroup --gid 1011 data-acc && usermod -a -G data-acc user
USER user
WORKDIR /home/user

# Create environment
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

WORKDIR /code
